### ISSUE TITLE
Environment Concept Art

### ISSUE THREAD

**Issue by fpdotmonkey** [fps-game-jam-org/open-game-jam-2020#58]

**Comment by MJ3dart** [comment]
![Tree 1](https://user-images.githubusercontent.com/71523858/93686470-8c9dcb80-fa84-11ea-96c2-372849533c35.png)
![Tree 2](https://user-images.githubusercontent.com/71523858/93686475-8f98bc00-fa84-11ea-9981-ba010f396476.png)
![Tree 3](https://user-images.githubusercontent.com/71523858/93686477-91fb1600-fa84-11ea-8366-9945c08ea954.png)

**Comment by MJ3dart** [comment]
Concept/idea

![Tree 4](https://user-images.githubusercontent.com/71523858/93686487-9f180500-fa84-11ea-83aa-0b5c71708689.png)

**Comment by MJ3dart** [comment]
//treeconcept

**Comment by MJ3dart** [comment]
![Nest](https://user-images.githubusercontent.com/71523858/93689424-684de900-fa9c-11ea-9868-0b86eab5b7a0.png)

**Comment by MJ3dart** [comment]
//Nestassets

**Comment by MJ3dart** [comment]
![Bush](https://user-images.githubusercontent.com/71523858/93693638-82a1ba00-fad0-11ea-983b-7dcd2835b169.png)

**Comment by MJ3dart** [comment]
//bushasset

**Comment by MJ3dart** [comment]
![Grass](https://user-images.githubusercontent.com/71523858/93694245-6d7c5980-fad7-11ea-85b4-ef1c90e4619e.png)

**Comment by MJ3dart** [comment]
Grass/ground tile

**Comment by MJ3dart** [comment]
![Foliage](https://user-images.githubusercontent.com/71523858/93694252-7ff69300-fad7-11ea-977b-1e2254d436ec.png)

**Comment by MJ3dart** [comment]
foliage/leavesfortrees

**Comment by MJ3dart** [comment]
![Fruit](https://user-images.githubusercontent.com/71523858/93694265-a74d6000-fad7-11ea-81e7-aa531b6e111b.png)

**Comment by MJ3dart** [comment]
Fruit

**Comment by MJ3dart** [comment]
![Background](https://user-images.githubusercontent.com/71523858/93724856-c51ed180-fb78-11ea-916d-1b349b5c31a3.png)
